"""Add factory_area_id to cameras table

Revision ID: 53f876f7612e
Revises: d7fe0aefe4c0
Create Date: 2025-10-18 21:16:38.329991+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f876f7612e'
down_revision = 'd7fe0aefe4c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###