"""Resync after manual schema changes

Revision ID: e621d949d068
Revises: 521bef1c7014
Create Date: 2025-10-19 00:53:16.749302+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e621d949d068'
down_revision = '521bef1c7014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_logs_employee_id'), 'employee_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_logs_id'), 'employee_logs', ['id'], unique=False)
    op.create_index(op.f('ix_employee_logs_timestamp'), 'employee_logs', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'cameras', 'factory_areas', ['factory_area_id'], ['id'], ondelete='SET NULL')
    op.add_column('employees', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('position_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('photo_front_path', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('photo_left_path', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('photo_right_path', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('face_embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('employees', sa.Column('violation_score', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_position_id'), 'employees', ['position_id'], unique=False)
    op.create_unique_constraint(None, 'employees', ['uuid'])
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employees', 'positions', ['position_id'], ['id'], ondelete='SET NULL')
    op.drop_column('employees', 'face_encoding')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'position')
    op.drop_column('employees', 'photo_url')
    op.drop_column('employees', 'face_embeddings')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.drop_column('users', 'hashed_password')
    op.add_column('violations', sa.Column('evidence_start_image', sa.String(length=500), nullable=True))
    op.add_column('violations', sa.Column('evidence_middle_image', sa.String(length=500), nullable=True))
    op.add_column('violations', sa.Column('evidence_end_image', sa.String(length=500), nullable=True))
    op.add_column('violations', sa.Column('person_tracker_id', sa.Integer(), nullable=True))
    op.add_column('violations', sa.Column('duration_frames', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violations', 'duration_frames')
    op.drop_column('violations', 'person_tracker_id')
    op.drop_column('violations', 'evidence_end_image')
    op.drop_column('violations', 'evidence_middle_image')
    op.drop_column('violations', 'evidence_start_image')
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'password_hash')
    op.add_column('employees', sa.Column('face_embeddings', sqlite.JSON(), nullable=True))
    op.add_column('employees', sa.Column('photo_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('employees', sa.Column('position', sa.VARCHAR(length=100), nullable=False))
    op.add_column('employees', sa.Column('department', sa.VARCHAR(length=100), nullable=False))
    op.add_column('employees', sa.Column('face_encoding', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_position_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_column('employees', 'violation_score')
    op.drop_column('employees', 'face_embedding')
    op.drop_column('employees', 'photo_right_path')
    op.drop_column('employees', 'photo_left_path')
    op.drop_column('employees', 'photo_front_path')
    op.drop_column('employees', 'position_id')
    op.drop_column('employees', 'department_id')
    op.drop_column('employees', 'uuid')
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_index(op.f('ix_employee_logs_timestamp'), table_name='employee_logs')
    op.drop_index(op.f('ix_employee_logs_id'), table_name='employee_logs')
    op.drop_index(op.f('ix_employee_logs_employee_id'), table_name='employee_logs')
    op.drop_table('employee_logs')
    # ### end Alembic commands ###