services:
  api:
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./app/static:/app/app/static
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
      - ./requirements.txt:/app/requirements.txt
      - ./README.md:/app/README.md
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app

  db:
    ports:
      - "5432:5432"
